"""Fix

Revision ID: 89c5bf31bafc
Revises: f857f4ff25e1
Create Date: 2024-03-13 19:31:48.816282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c5bf31bafc'
down_revision: Union[str, None] = 'f857f4ff25e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('game_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'game_type')
    # ### end Alembic commands ###
